dist: trusty
language: ruby
cache: bundler
rvm:
- 2.3.1
#- 2.2
#- 2.1
before_install: gem update --system
install: bundle install
script:
- bundle exec jekyll build
#matrix:
#  allow_failures:
#    - rvm: 2.1
#    - rvm: 2.3
notifications:
  irc:
    channels:
      - "chat.freenode.net#tigefa"
      - "chat.freenode.net##tigefa"
    nick: tigefa
    password:
      secure: "cc20DwyhL1hL0wjKFcvElbxRrkHuXcFne1l0g7dXYc4reJnJCJnxkKylYEkjxtv6hOOHwoeLd8i8937FXXa0ky0dkZ3hnRmL2kkxjMb+qI4DDae0RSVvWs9GPe1elaScEfK4rH9E0Q/1zU9/YXxXQWsrAyjY8TE+Bi0Yx00Sl78="
  campfire:
    rooms:
    - tigefa1:0ae60ba741d05cbd1a1435c5137ac3d856cd96ed@595196
    template:
    - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
    - 'Build details: %{build_url}'
  email: false
  hipchat:
    rooms:
      secure: GrNQ+RMl/AKxaR07B6f0PU40J5HbyriGUIotLpHAPlpuMkOduUksSLz2VhlS8n5HKS3zPD60nmxDA8UIR15cOojYoY7lIynd0MkSo1zVo3oEeS22qCqIA0vDxF/atLow9F4dyCGlALLdgsE1stbyitUd2KTecMP4O+cE39UQBT0=
