dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.3
#before_install: gem update --system
#install: bundle install
script:
- bundle exec jekyll build
notifications:
  irc:
    channels:
    - chat.freenode.net#tigefa
    - chat.freenode.net#tigefarb
    - chat.freenode.net##tigefa
  campfire:
    rooms:
      secure: CkMzTewoccyvhdbvxkutepD0gcvLbMi6TZU5le7kKwdKLKqodPs2B25ztb9raZR6GwygNH0wG2O3DjXUlsSnV/0/p0NW5TuVhZvQcxCw3UgP2w7n6FZCP5azZCzsSbhLYPasNUcF714NZ5cRP2ouFaWNsM+Gy6AkoVF1QXLIHGI=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{build_url}"
    - 'Build details: %{build_url}'
  email: false
  slack:
    rooms:
      - tigefa:Ru9WZPQ79qA7Epq0zOPnozqA#general
      - tigefa:Ru9WZPQ79qA7Epq0zOPnozqA#random
      - tigefa:Ru9WZPQ79qA7Epq0zOPnozqA#stream

  hipchat:
    rooms:
      - 17f23bd56e72c930ab445af788dd54@3482868
      - 17f23bd56e72c930ab445af788dd54@52330
      - 17f23bd56e72c930ab445af788dd54@3544496
    format: html
