language: ruby
before_install:
  - gem install bundler
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
script: bundle exec rake
notifications:
  irc: "irc.freenode.org#tigefa"
  email:
    on_success: never
    on_failure: never