language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
before_install:
  - gem update --system
  - gem --version
  - bundle install
install: gem install github-pages
script: "bundle exec jekyll build"
bundler_args: --without development debug
notifications:
  email: false
