language: ruby
rvm:
  - 2.1
  - 2.0.0
  - 1.9.3
script:
#  - bundle exec jekyll build
  - bundle exec rake
notifications:
  irc:
    channels:
      - "irc.freenode.org#tigefa"
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
  campfire:
    rooms:
      - tigefa1:0ae60ba741d05cbd1a1435c5137ac3d856cd96ed@595196
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
  email:
    on_success: never
    on_failure: never
