language: ruby
before_install:
  - bundle install
rvm:
  - 2.0.0
  - 1.9.3
script:
  - bundle exec rake coveralls
  - bundle exec jekyll build
notifications:
  email:
    on_success: never
    on_failure: never
