language: ruby
before_install:
  - gem --version
  - bundle install
rvm:
  - 2.0.0
  - 1.9.2
  - 1.8.7
install: gem install github-pages --development
script: "bundle exec jekyll build"
notifications:
  email:
    on_success: never
    on_failure: never
