name: tigefa4u.github
safe: true
lsi: false
pygments: true
markdown: kramdown
permalink: /:year/:month/:title.html
relative_permalinks: false
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
#name: sugeng tigefa
google_analytics_id: UA-29791208-1
disqus_shortname: tigefa
url: http://tigefa4u.github.io
#baseurl: /project-name
twitter: tigefa_team
github: tigefa4u
gravatar_url: /images/github.png
timezone:    Aisa/Jakarta
bitbucket: tigefa4u
googleplus: tigefa
smileytheme: MSN
