# Site settings
title: sugeng tigefa
email: sugeng@tigefa.xyz
description: Awesome word for reasons
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tigefa4u.github.io" # the base hostname & protocol for your site
author:
  name:    sugeng tigefa
  twitter: sugeng_tigefa
  github:  tigefa4u
  disqus:  tigefa4u

analytics:
      google:
      yandex:

# Build settings
markdown: kramdown
highlighter: rouge
timzone: Asia/Jakarta
permalink: /articles/:day-:month-:year-:title.html
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

exclude: ["docs", "Jenkinsfile", "Dockerfile", "CODE_OF_CONDUCT.md", ".sass-cache", "Rakefile", "Rakefile.rb", "tmp", "venv", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "vendor", ".c9", "appveyor.yml", "circle.yml", "iron.json", "composer.json", "tigefa.jquery.json"]
