# Site settings
title: tigefa4u
email: sugeng@tigefa.org
description: "Writing posts from repostories Github"
url: "http://gitid.pw"
baseurl: ""
twitter_username: sugeng_tigefa
github_username:  tigefa4u
facebook_username:  tigefa

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /articles/:title.html
relative_permalinks: false
paginate: 5
paginate_path: /page/:num
timezone: Aisa/Jakarta
exclude: [Gemfile, Gemfile.lock, vendor, docs, dist, Gruntfile.js, package.json, composer.json, CNAME, LICENSE, iron.json]
