safe: true
lsi: false
pygments: true

title:        tigefa4u
tagline:      'Writing posts from repostories Github'
description:  'Writing posts from repostories Github.'
url:          http://tigefa.pw
version:      3.1.1
author:
  name:       'sugeng tigefa'
  email:      'sugeng@tigefa.org'

markdown:     kramdown
permalink:    /articles/:title.html

paginate:     5
paginate_path: /page/:num
relative_permalinks: false
timezone:    Aisa/Jakarta

exclude: [Gemfile]
