# Site settings
title: sugeng tigefa
email: sugeng@tigefa.xyz
description: Awesome word for reasons
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tigefa.space" # the base hostname & protocol for your site
author:
  name:    sugeng tigefa
  twitter: sugeng_tigefa
  github:  tigefa4u
  disqus:  tigefa4u

analytics:
      google:
      yandex:

# Build settings
markdown: kramdown
highlighter: rouge
timzone: Asia/Jakarta
permalink: /articles/:day-:month-:year-:title.html
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

exclude: [".sass-cache", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "vendor", ".c9"]
