safe: true
lsi: false
pygments: true
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

title:        tigefa4u
tagline:      'Writing posts from repostories Github'
description:  'Writing posts from repostories Github.'
url:          http://tigefa.pw
version:      3.1.1
author:
  name:       'sugeng tigefa'
  email:      'sugeng@tigefa.org'
  
repo:
  project: https://github.com/tigefa4u/tigefa4u.github.io
  profile: https://github.com/tigefa4u

markdown:     kramdown
permalink:    /articles/:title.html

paginate:     5
paginate_path: /page/:num
relative_permalinks: false
timezone:    Aisa/Jakarta

exclude: [Gemfile, Gemfile.lock, vendor, docs, dist, Gruntfile.js, packages.json, composer.json, CNAME, LICENSE, LICENSE.md]
