# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sugeng tigefa
email: sugeng@tigefa.xyz
description: Awesome word for reasons
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tigefa.space" # the base hostname & protocol for your site
author:
  name:    sugeng tigefa
  twitter: sugeng_tigefa
  github:  tigefa4u
  disqus:  tigefa4u

analytics:
      google:
      yandex:

# Build settings
timzone: Asia/Jakarta
permalink: /articles/:year-:month-:day-:title.html
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "vendor", ".c9"]
