name:     tigefa4u
markdown: redcarpet
safe:     true
lsi:      false
pygments: false

# Meta
meta:
  description: Writing posts from repostories Github
  keywords:    rails, openshift, pagodabox, deployment, tutorial, how git, git deploy, ruby tutorial, ruby on rails

author:
  name:       sugeng tigefa
  email:      sugeng@tigefa.org
  twitter:    tigefa_team
  facebook:   tigefa.team
  googleplus: tigefasugeng
  vimeo:      tigefa
  
# Comments
comment:
  disqus: tigefa4u

# Gems
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# Permalink URL
url:                 http://tigefa.pw
permalink:           /articles/:title.html
relative_permalinks: false

# CDN
cdn:
  raw:            https://raw.githubusercontent.com/tigefa4u/tigefa4u.github.io/master
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
  jquery:         //ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
  FontAwesome:    //netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.min.css

# Pagination and Variables
paginate:       5
paginate_path: /page/:num
timezone:      Aisa/Jakarta

exclude: [Gemfile, Gemfile.lock, vendor, docs, dist, Gruntfile.js, packages.json, composer.json, CNAME, LICENSE, LICENSE.md]