# Site settings
title: tigefa4u
tagline: write stuff from Github
email: tigefa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m a professional UI/UX designrer and web developer. 
  I love being minimal and creative.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gitid.pw" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "sugeng tigefa"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: tigefa4u
    twitter: sugeng_tigefa
    facebook: tigefa
    gplus: +tigefasugeng
    # dribble: gayanvirajith
    pinterest: tigefa

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
