safe: true
lsi: false
pygments: false

title:        tigefa4u write tutorials
tagline:      'Writing posts from repostories Github'
description:  'An elegant open source and mobile first theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:          http://tigefa.pw
version:      3.0.0
author:
  name:       'sugeng tigefa'
  email:      'sugeng@tigefa.org'

markdown:     kramdown
permalink:    /articles/:title.html

paginate:     5
paginate_path: /page/:num
relative_permalinks: false
timezone:    Aisa/Jakarta

exclude: [Gemfile]
