# Site settings
title: Sugeng Tigefa
description: > # this means to ignore newlines until "baseurl:"
  A personal note and some stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
timezone: Aisa/Jakarta
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
gems: [jekyll-paginate]

# Permalinks
port: 80
host: sugeng.dev
permalink: /articles/:title.html
relative_permalinks: false
gcse: 006270711061491111331:vsivtajjjh0
# comments
disqus: tigefa4u # add disqus shortname here

exclude: 
  - docs
  - vendor
  - Gemfile.lock

# author info
# add your appropriate info here
author: Sugeng Tigefa # your name
bio:    # your bio
email: tigefa@gmail.com
email_md5: 6fcda63de411a2c52be42fd1055d63b0 # md5 hash of your email
twitter_username: sugeng_tigefa
github_username: tigefa4u

# Theming options
# These settings are mandatory.
theme:              'blue-grey'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
