platform:
  - x86
  - x64

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - git --version

build: off

test_script:
#  - ps: Install-Product ruby $env:ruby_version
  - set RUBY_VER=2.1
  - bundle install
  - bundle exec jekyll build

environment:
  matrix:
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"