environment:
  ruby_version: "2.1"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - git --version

build: off

test_script:
#  - ps: Install-Product node $env:ruby_version
  - set RUBY_VER=2.1
  - bundle install
  - bundle exec jekyll build