platform:
  - x86
  - x64

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
#  - gem update --system
  - gem install bundler
  - bundle install

build: off

#cache:
#  - vendor/bundle

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
#  - bundle config --local path vendor/bundle
  - bundle exec jekyll build

environment:
  matrix:
#    - ruby_version: "200"
#    - ruby_version: "21"
#    - ruby_version: "22"
    - ruby_version: "23"
    - ruby_version: "24"

#matrix:
#  fast_finish: true
#  allow_failures:
#    - ruby_version: "21"
#    - ruby_version: "22"
#    - ruby_version: "23"
