# Default image format
format                  :      gif

# Default shortcuts for smileys
rock                    :      "(\\\\m\\/)"
wink                    :      "(;-?\\))"
grin                    :      "(:-?D)"
cool                    :      "((?:B|8)-?\\))"
kiss                    :      "(:-?\\*)"
smile                   :      "(:-?\\))"
frown                   :      "(:-?\\()"
heart                   :      "((?:<|&lt;)3)"
angry                   :      "((?:X|>|&gt;)-?\\()"
shout                   :      "((?:>|&gt;)\\.(?:&lt;|<))"
angel                   :      "((?:0|O):-?\\))"
alien                   :      "(\\(\\.v\\.\\))"
devil                   :      "(\\}:-?\\))"
crying                  :      "(:(?:'|&#8217;)-?\\()"
confused                :      "(:-?(?:S|\\?))"
surprised               :      "(:-?(?:O|0))"
tongue-out              :      "(:-?P)"
speechless              :      "(:-?\\|)"
lips-sealed             :      "(:-?X)"
broken-heart            :      "((?:<|&lt;)\\/3)"

# Smileys without shortcuts
blush                   :      ""
dozing                  :      ""
embarrassed             :      ""
in-love                 :      ""
peace                   :      ""
thumbs-up               :      ""
thumbs-down             :      ""
sleepy                  :      ""
sick                    :      ""
clap                    :      ""
vomit                   :      ""
pray                    :      ""
whistle                 :      ""
