version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic
    steps:
      - checkout
      - run:
          name: Install and Update Packages
          command: |
            export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
            apt-get update && apt-get dist-upgrade -y
            apt-get install -y sudo apt-utils apt-transport-https ca-certificates wget curl netcat aria2 python-pip python3-pip
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs build-essential ruby ruby-dev
            sudo -E -H npm install --global npm@latest
            sudo -E -H npm install --global node-gyp
            sudo -E -H npm install --global node-pre-gyp
            sudo -E -H npm install --global yarn
            yarn
            gem install bundler
            bundle install --jobs=$(nproc)
      - run:
          name: Test
          command: |
            bundle exec rake test
